$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        280:{
            items:2
        },
        580:{
            items:3
        },
        768:{
            items:5
        }
    },
})